# Generated by Django 3.0.7 on 2020-06-24 19:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
