# Generated by Django 3.0.7 on 2020-07-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200624_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='tutorial_cat_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='tutorials',
            name='tutorial_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='tutorial_series_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
